# Generated by Django 3.0.5 on 2020-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_internet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='issuer_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
