# Generated by Django 3.0.5 on 2020-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_internet_app', '0002_inquiry_issuer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
