# Generated by Django 3.0.5 on 2020-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_internet_app', '0003_auto_20200618_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='is_open',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='open_for_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='website_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
